config/routes.rb
Rails.application.routes.draw do
  resources :comments
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get 'home/index', as: :index

  get 'home/regalos', as: :regalos
  root to:  'home#portada'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: %i[ show edit update destroy ]

  # GET /comments or /comments.json
  def index
    @comment = current_user.comments.new
  end

  # GET /comments/1 or /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments or /comments.json
  def create
    @comment = current_user.comments.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to root_path, notice: "Mensaje enviado con éxito, gracias por los buenos deseos a la pareja" }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1 or /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to comment_url(@comment), notice: "Comment was successfully updated." }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1 or /comments/1.json
  def destroy
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to comments_url, notice: "Comment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def comment_params
      params.require(:comment).permit(:name, :message, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

    before_action :authenticate_user!

    def index
        
    end

    def regalos
        
    end

    def portada
        
    end
    
    
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/comments/_form.html.erb
<%= form_with(model: comment) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
        <% comment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :message %>
    <%= form.text_area :message %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<div id="Principal">
  <div id="card-comentarios"class="animate__animated animate__backInDown animate__delay-1s">
    <div id="div-comentarios">
      <i class=" margin-top fas fa-comments letra-blanca tamano-85 margin-bottom margin-top"></i>
      <p class=" tamano-20 letra-blanca margin-0 paddig letra-cursiva mensaje-comentarios">Una Boda se vive tres veces, </p>
      <p class="tamano-20 letra-blanca margin-0 paddig letra-cursiva mensaje-comentarios">Al Soñarla, al Celebrarla, al Recordarla</p>
      <p class="tamano-20 letra-blanca margin-0 paddig letra-cursiva mensaje-comentarios"> Dejanos tus Deseos</p>

      <section class="section">
        <%= form_with(model: @comment, remote: true) do |form| %>
          <%= form.text_field :name, id:'nombres', placeholder: 'Tu nombre aquí', class:"casillas"%>

            <div class="field">
              <%= form.text_area :message, class:'casillas', id:"comentarios", placeholder:"Deja tu mensaje aquí", rows:5%>
            </div>

            <div class="actions">
              <%= form.submit 'Enviar', class:'boton letra-molde tamano17' %>
            </div>
        <% end %>

      </section>
    </div>
  </div>
</div>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @comment.name %>
</p>

<p>
  <strong>Message:</strong>
  <%= @comment.message %>
</p>

<p>
  <strong>User:</strong>
  <%= @comment.user_id %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/home/index.html.erb
<div id="Principal" >
    <div id="card"class="animate__animated animate__backInDown animate__delay-1s">
        <div id="Bienvenida">
            <p class="margin-top margin-bottom tamano-65 letra-cursiva" id="mensaje-bienvenida">Bienvenidos a la boda de Jacqueline & Luis</p>
            <div class="contenedor-imagen img  "></div>
            <p class="pulsa letra-molde tamano17" id="boton-zoom">Pulsa para unirte a la Santa Eucaristía</p>
            <a href="https://www.facebook.com/events/464033015218444/?ref=newsfeed" class="boton-zoom letra-molde" target="_blank"><b>Facebook Live</b></a>
            <div>
                <i class="far fa-arrow-alt-circle-down" id="flecha"></i>
            </div>
        </div>

        <div id="comentario-regalo">
            <div id="comentario">
                <%= link_to 'Comentarios para el recuerdo', comments_path, class:"letra-blanca tamano-20" %>
                <%= link_to comments_path do %>
                    <i class="fas fa-comments letra-blanca tamano-65 margin-bottom margin-top"></i>
                <% end %>
            </div>
            <div class="linea"></div>
            <div id="regalo">
                <%= link_to 'Obsequios', regalos_path, class:"letra-blanca tamano-20" %>
                <%= link_to regalos_path do %>
                    <i class="fas fa-gift tamano-65 letra-blanca margin-top margin-bottom"></i>
                <% end %>
            </div>

        </div>
    </div>
</div>

app/views/home/portada.html.erb
<div id="principal">
    <div id="div-bienvenida">
        <p class="color-blanco margin-bottom margin-top letra-molde letra-pequena">Bienvenidos a la boda de Jacqueline & Luis</p>
        <%= link_to 'Pulsa aquí', index_path, class: 'color-blanco letra-pequena borde txt-non letra-cursiva boton-portada' %>
    </div>
    <%= link_to 'Cerrar Sesión', destroy_user_session_path, method: :delete, class:'cerrar-sesion' %>
</div>

app/views/home/regalos.html.erb
<div id="Principal-regalos">
    <div id="card-regalo"class="animate__animated animate__backInDown animate__delay-1s">
        <div id="div-regalo">
            <p class="centrado margin-bottom-0 margin-0 paddig letra-blanca tamano-42 letra-cursiva" id="bienvenida-regalos"> Su participación virtual en nuestra boda es el mejor regalo para nosotros, 
            <p Class=" tamano-20 centrado margin-0 paddig letra-blanca tamano-mediano letra-molde"> pero si desea hacernos un regalo para nuestra nueva vida juntos,
            </p>
            <p class=" tamano-20 centrado margin-0 paddig letra-blanca tamano-pequeno letra-molde tamano-mediopequeno "><u>puede depositarlo al:</u></p> 
            </p>
            <p class=" tamano-20 centrado margin-0 paddig letra-blanca tamano-pequeno letra-molde tamano-mediopequeno">(banco de desarrollo rural, Banrural)
            </p>
            <p class=" tamano-20 centrado margin-0 paddig letra-blanca tamano-pequeno letra-molde tamano-mediopequeno"> Cuenta Monetaria</p>
            <p class=" tamano-20 centrado margin-0 paddig letra-blanca tamano-pequeno letra-molde "> 3509044298</p>
            <p class=" tamano-20 centrado margin-bottom-0 paddig letra-blanca tamano-pequeno letra-molde tamano-mediopequeno">A nombre de:</p>
            <p class=" tamano-20 centrado margin-0 paddig letra-blanca tamano-20 letra-cursiva "> Jacqueline Ramazzini</p>
            
            <p class=" bold tamano-20 centrado linea-abajo-texto margin-bottom-0 paddig letra-blanca tamano-pequeno letra-molde tamano-mediopequeno "><u>O pueden hacernoslo llegar a:</u></p>
            <p class=" tamano-20 centrado margin-0 paddig letra-blanca tamano-pequeno letra-molde tamano-mediopequeno ">
                Km 19.8 Calle Las Manzanillas, Condominio Los Manzanillos casa 2
            </p>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BodaJL</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@200&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Great+Vibes&family=Lora:ital@1&family=Montserrat:wght@300&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" >

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p style="display: <%= 'none' if notice.nil? && alert.nil?%>" class="letra-molde alerta">
      <%= alert %>
      <%= notice %>
    </p>
    <%= yield %>
    <%= render 'partials/footer'%>
  </body>
</html>

app/views/partials/_footer.html.erb
<div id="JyF">
    <p class="letra-molde tamano-chiquito ">Desarrollado por Fátima Ramazzini</p>
</div>